import sys
import os

# Add the root directory to sys.path so we can import from src
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.engine.current_build.workflow import run_agentic_workflow

if __name__ == "__main__":
    print("=== DÉMARRAGE DU SYSTÈME MULTI-AGENT ===")
    
    # Define the user's request
    user_request = "Une application web simple avec une page HTML, du CSS pour le style, et un script JS qui affiche 'Bonjour le monde' dans la console."
    
    # Run the full workflow
    try:
        final_state = run_agentic_workflow(
            user_prompt=user_request,
            functional_specs="" # Specs will be generated by the Concepteur
        )
        
        print("\n[SUCCES] Exécution terminée !")
        print(f"Dernier agent actif: {final_state.get('current_agent')}")
        
    except Exception as e:
        print(f"[ERREUR] Erreur lors de l'exécution : {e}")
